name: 'seedwing-action'
description: 'Apply seedwing policies to your project'
author: 'seedwing-io team'
branding:
  icon: play-circle
  color: black
inputs:
  policy-dir:
    description: Additional policies to use for enforcement
    required: true
  name:
    description: Policy name to check
    required: true
  input:
    description: File containing the contents input to the policy checker. Relative to the project directory.
    required: true
outputs:
  rationale:
    description: 'Description of the policy decision'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.policy-dir }}
    - ${{ inputs.name }}
    - ${{ inputs.input }}
