name: 'policy-action'
description: 'Apply seedwing policies to your project'
author: 'seedwing-io team'
branding:
  icon: play-circle
  color: black
inputs:
  config:
    description: Optional location of Seedwing.toml file (project root by default).

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.config }}
